services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    ports:
      - "3000:3000"
    networks:
      - app-network
    volumes:
      - ./src:/app/src
      - /app/node_modules

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "4200:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
