services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    ports:
      - "3000:3000"
    network_mode: host # Permet au conteneur d'accéder à localhost

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "4200:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
