services:
  couchbase:
    image: couchbase:latest
    container_name: couchbase
    ports:
      - "8091:8091"  # Port d'administration
      - "8092:8092"  # API
      - "8093:8093"  # Service de requêtes
      - "8094:8094"  # Recherche
      - "8095:8095"  # Analytics
      - "8096:8096"  # Eventing
      - "11210:11210"  # Data service
    volumes:
      - ./couchbase-data/data:/opt/couchbase/var  # Dossier des données persistantes
      - ./init-scripts:/etc/couchbase/init-scripts  # Dossier pour les scripts d'initialisation
    environment:
      - COUCHBASE_ADMINISTRATOR_USERNAME=user1
      - COUCHBASE_ADMINISTRATOR_PASSWORD=password
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8091/ui/index.html"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s
    restart: unless-stopped
    entrypoint: ["/bin/bash", "/etc/couchbase/init-scripts/init.sh"]  # Exécuter le script d'initialisation


  # Backend NestJS
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    ports:
      - "${BACKEND_PORT:-3000}:3000"
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - BACKEND_PORT=3000
      - BASE_PATH=/app
      - DB_HOST=couchbase://couchbase
      - DB_PORT=${DB_DOCKER_PORT:-8092}
      - DB_USER=${DB_USER:-user1}
      - DB_PASSWORD=${DB_PASSWORD:-password}
      - BUCKET_NAME=${BUCKET_NAME:-ProductsBDD}
      - USER_BUCKET_NAME=${USER_BUCKET_NAME:-UsersBDD}
      - CATEGORY_BUCKET_NAME=${CATEGORY_BUCKET_NAME:-CategoryBDD}
      - BRAND_BUCKET_NAME=${BRAND_BUCKET_NAME:-BrandsBDD}
      - INDEX_NAME=${INDEX_NAME:-ProductsBDD._default.IndexTest}
      - JWT_SECRET=${JWT_SECRET:-a3f1b2c5d6e8f9g1a2b3c4d5e6f7g8h9i0j1k2l3m4n5o6p7}
      - UNSPLASH_ACCESS_KEY=${UNSPLASH_ACCESS_KEY:-nuVp2_81YPnvvJ3g87X9AtIUhURRh-WVaxeR1p40OwY}
      - URL_FRONTEND=http://frontend
      - URL_BACKEND=http://backend:3000/data
      - DISABLE_SSL=true
    depends_on:
      couchbase:
        condition: service_healthy
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped

  # Frontend Angular
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "${FRONTEND_PORT:-4200}:80"
    environment:
      - URL_FRONTEND=http://localhost:${FRONTEND_PORT:-4200}
      - URL_BACKEND=http://localhost:${BACKEND_PORT:-3000}/data
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  couchbase_data:
    driver: local