services:
  couchbase:
    image: couchbase/server:latest
    container_name: couchbase
    ports:
      - "8091:8091" # Port d'administration
      - "8092:8092" # API
      - "8093:8093" # Service de requêtes
      - "8094:8094" # Recherche
      - "8095:8095" # Analytics
      - "8096:8096" # Eventing
      - "11210:11210" # Data service
    env_file:
      - .env.docker
    environment:
      - DB_USER
      - DB_PASSWORD
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8091/ui/index.html"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s
    restart: unless-stopped
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    ports:
      - "${BACKEND_PORT:-3000}:3000"
    env_file:
      - .env.docker
    environment:
      - DB_HOST=couchbase://couchbase
      - API_URL=http://backend:3000
    depends_on:
      couchbase:
        condition: service_healthy
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "${FRONTEND_PORT:-4200}:80"
    env_file:
      - .env.docker
    depends_on:
      - backend
    restart: unless-stopped
  nginx-proxy:
    image: nginx:alpine
    ports:
      - "8081:80"
    volumes:
      - ./nginx-proxy.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
volumes:
  couchbase_data:
    driver: local
networks:
  default:
    driver: bridge